### ISSUE TITLE
Activate fabricjs canvas and draw using mouse event listeners

### ISSUE THREAD

**Issue by Kampii** [altert/OpenseadragonFabricjsOverlay#2]
First of all - I haven't started to test this jet, but it looks amazing!

Do you think this is possible?

**Comment by altert** [comment]
It is possible, but not in current state of plugin. You can try it out in demo - activate Fabric freedrawing mode
by `overlay.fabricCanvas().isDrawingMode=true;` and disable OSD mousevents with `self.viewer.setMouseNavEnabled(false);`. But I guess there is some conflict with mouse up events of Fabric and OSD. There is another way though. You can make div with z-index higher than OSD canvas with the same dimensions, and sync it to OSD in the same matter as done in plugin.

**Comment by Kampii** [comment]
Thanks a lot! I will look into this and try to make it work. Yesterday I came up with [this test](http://www.c-ev.com/osdragon/dragonfabric1.html) which is a very poor version of what you have. I just got an insane jump start!

**Comment by altert** [comment]
I've updated demo with freedrawing example with events conflict resolved.

**Comment by Kampii** [comment]
Cool.. I'll take a look.

**Comment by Kampii** [comment]
omg.. this is exactly what I need. How do you stop drawing/ switch back to zoom?

**Comment by altert** [comment]
reverse what's in demo, add tracking back to OSD
`self.viewer.setMouseNavEnabled(true);`
`self.viewer.outerTracker.setTracking(true);`
disable freedrawing mode
`overlay.fabricCanvas().isDrawingMode=false;`

I think control for that should be outside drawing area though

**Comment by Kampii** [comment]
Perfect, i'm so excited. Thank you a lot!

**Comment by altert** [comment]
np. good luck with your project)

**Comment by Kampii** [comment]
I am not able to locate the isDrawingMode property in order to set it false. It is not under App.viewer nor under App.overlay.. Where is it? I am trying to run this `overlay.fabricCanvas().isDrawingMode=false;` from the browsers console.
