### ISSUE TITLE
Black line when drawing

### ISSUE THREAD

**Issue by pipriles** [altert/OpenseadragonFabricjsOverlay#23]
Hello, i have an issue that happens only the first time you draw with freeDrawing.

![screenshot at 2017-07-31 06-07-07](https://user-images.githubusercontent.com/11748638/28773377-4d74f456-75b7-11e7-9bb7-ebd17ec96cdd.png)

If i release the mouse button it shows the desired line, and the behavior is strange.
Thank you.

**Comment by altert** [comment]
Could you include browser/operating system that you use?

**Comment by pipriles** [comment]
Chrome 59.0.3071.115 / GNU Linux
