### ISSUE TITLE
How to align the overlay together with Openseadragon canvas

### ISSUE THREAD

**Issue by Kampii** [altert/OpenseadragonFabricjsOverlay#3]
What is the correct approach to align the overlay with the Openseadragon in case it has left and/or top offset?

What I tried is I aligned the contentDiv 80px from the left.

```
        <div id = "contentDiv"
        class = "openseadragon1"
        style = "float: right;
        background: black;
        width: 400px;
        left: 80px"
        ></div> 
```

That moved the overlay elements 80px to the right so in the openseadragon-fabricjs-overlay.js I changed the canvasdiv.style.left to -80px

```
         ..
         this._canvasdiv = document.createElement( 'div');
         this._canvasdiv.style.position = 'absolute';
         this._canvasdiv.style.left = "-80px";
         this._canvasdiv.style.top = 0;
        this._canvasdiv.style.width = '100%';
```

That solved the problem with different scaling between overlay and contentDiv, however, now the rightmost side of the overlay is not displayed, it is sort of cut off. It looks like changing the _canvasdiv.style.left is the incorrect way to do it.

**Comment by altert** [comment]
Try new version 0.0.2, I've modified positioning code

**Comment by Kampii** [comment]
It looks like the initial problem is solved, however, now there is this "shivering" effect. When you zoom in our out the fabricjs element follows by increments. I'll make a screencast.

**Comment by Kampii** [comment]
So [here](http://c-ev.com/osdragon/fabricoverlay/shivering.mov) is the screencast. In the first part I am messing with the demo and in the second part of the video I am showing how it works with the v0.0.1.

**Comment by altert** [comment]
try  b28ff07 (0.0.2), I updated positioning code again

**Comment by Kampii** [comment]
Runs beautifully! Thanks!
