### ISSUE TITLE
Could you please update fabric.adapted.js to 2.2.3v

### ISSUE THREAD

**Issue by DimaSavchenko** [altert/OpenseadragonFabricjsOverlay#31]
I require openseadragon-fabricjs-overlay/fabric/fabric.adapted.js

And I get errors: 
`Can't resolve 'canvas' in 'D:\projects\phoenix\node_modules\openseadragon-fabricjs-overlay\fabric'`
`Can't resolve 'jsdom' in 'D:\projects\phoenix\node_modules\openseadragon-fabricjs-overlay\fabric'`

But when I require fabric/dist/fabric, I do not get any errors. 
Maybe it is time for updating OpenseadragonFabricOverlay(vabric 1.7.17v). The Fabric has version 2.2.3. 
Thanks

**Comment by Spenstar** [comment]
+1 to this request. v2 has added new event listeners that are greatly needed.

**Comment by QingMings** [comment]
+1

**Comment by sathishravula** [comment]
please update to latest version 2.2.3 and i am not able to edit the text

**Comment by Sherry-Xu-2018** [comment]
+1

**Comment by jetic83** [comment]
+1

**Comment by CrazyCrud** [comment]
+1

**Comment by mfiers** [comment]
+1

**Comment by altert** [comment]
see #46
