### ISSUE TITLE
Overlay not resized when window size changes

### ISSUE THREAD

**Issue by Kampii** [altert/OpenseadragonFabricjsOverlay#4]
Hi,

If I understand correctly, then this code

```
$(window).resize(function() {
                         overlay.resize();
                     });
```

is responsible for resizing the overlay together with the window when the window size gets changed, however, the overlay in the demo page does not resize. I'm using Chrome 48.0.2564.116. The same thing on Safari 8.0.3 (10600.3.18). Is there any way to fix it?

**Comment by altert** [comment]
That was a bug, see c81fba2 for fix

**Comment by Kampii** [comment]
Resize now works great!
