### ISSUE TITLE
dependency issue to openseadragon

### ISSUE THREAD

**Issue by lwjason** [altert/OpenseadragonFabricjsOverlay#8]
I found that the compatible version of openseadragon actually is not  2.0.0 up, 2.1.0 instead.

v2.1.0 added some new functions in the TiledImage class, and one that makes the error is the viewportToImageZoom function. It was added since v2.1.0.

So if someone like me installs OpenseadragonFabricjsOverlay from bower and follows the dependency requirement openseadragon#2.0.0 ... BOOM!

![image](https://cloud.githubusercontent.com/assets/8266796/16758300/57215b22-4843-11e6-96b7-54d8b2803ff3.png)

**Comment by altert** [comment]
thanks!
